apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - releaseName: echo
    namespace: default
    repo: https://bjw-s-labs.github.io/helm-charts
    name: app-template
    version: 4.5.0
    valuesFile: values.yaml
